openapi: "3.0.0"
info:
  title: "Бэкенд для Trello"
  version: "0.1.0"
tags:
  - name: User
  - name: Board
  - name: Row
  - name: Task
paths:
  /auth:
    post:
      tags:
        - User
      description: Авторизация пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: Авторизация прошла успешно

        400:
          description: Запрос сформирован неверно
        403:
          description: Авторизация неуспешна
  /users:
    post:
      tags:
        - User
      description: Регистрация нового пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationRequest"
      responses:
        200: 
          description: Пользователь успешно зарегистрирован
        400:
          description: Запрос сформирован неверно
        409:
          description: Уже создан пользователь с таким email
  /users/{id}:
    parameters:
      - name: id
        description: ID пользователя
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - User
      description: Получение информации о пользователе
      responses:
        200:
          description: Информация получена
        401:
          description: Неавторизованный запрос
        404:
          description: Пользователь не найден
    patch:
      tags:
        - User
      description: Получение информации о пользователе
      responses:
        200:
          description: Информация получена
        403:
          description: Недостаточно прав
        404:
          description: Пользователь не найден
        400:
          description: Запрос сформирован неверно
    delete:
      tags:
        - User
      description: Получение информации о пользователе
      responses:
        200:
          description: Информация получена
        404:
          description: Пользователь не найден
        403:
          description: Недостаточно прав
          
  /boards:
    get:
      tags:
        - Board
      description: Получение списка досок пользователя
      responses:
        200:
          description: Доски успешно получены
        401:
          description: Неавторизованный запрос
    post:
      tags:
        - Board
      description: Создание доски
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostBoardsRequest"
      responses:
        200:
          description: Доска успешно создана
        401:
          description: Неавторизованный запрос
        400:
          description: Запрос сформирован неверно
  /boards/{id}:
    parameters:
      - name: id
        description: Уникальный идентификатор доски
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Board
      description: Получение доски
      responses:
        200:
          description: Доска успешно получена
        401:
          description: Неавторизованный запрос
        404:
          description: Доска не найдена
    patch:
      tags:
        - Board
      description: Изменение доски
      responses:
        200:
          description: Доска успешно изменена
        401:
          description: Неавторизованный запрос
        404:
          description: Доска не найдена
        400:
          description: Запрос сформирован неверно
    delete:
      tags:
        - Board
      description: Удалeние доски
      responses:
        200:
          description: Доска удалена
        401:
          description: Неавторизованный запрос
        403:
          description: Недостаточно прав
  /rows:
    post:
      tags:
        - Row
      description: Добавление столбца на доску
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostRowsRequest"
      responses:
        200:
          description: Столбец добавлен
        401:
          description: Неавторизованный запрос
        400:
          description: Запрос сформирован неверно
  /rows/{id}:
    parameters:
      - name: id
        description: ID столбца
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Row
      description: Получение содержимого столбца
      responses:
        200:
          description: Столбец получен
        401:
          description: Неавторизованный запрос
        404:
          description: Столбец не найден
    patch:
      tags:
        - Row
      description: Изменение столбца
      responses:
        200:
          description: Столбец успешно изменен
        401:
          description: Неавторизованный запрос
        404:
          description: Столбец не найден
        400:
          description: Запрос сформирован неверно
    delete:
      tags:
        - Row
      description: Удаление столбца
      responses:
        200:
          description: Столбец успешно удален
        401:
          description: Неавторизованный запрос
        404:
          description: Столбец не найден
  /tasks:
    post:
      tags:
        - Task
      description: Добавление задания
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostTasksRequest"
      responses:
        200:
          description: Задание добавлено
        401:
          description: Неавторизованный запрос
        400:
          description: Запрос сформирован неверно
  /tasks/{id}:
    parameters:
      - name: id
        description: ID задания
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Task
      description: Получение задания
      responses:
        200:
          description: Задание получено
        401:
          description: Неавторизованный запрос
        404:
          description: Задание не найдено
    patch:
      tags:
        - Task
      description: Изменение задания
      responses:
        200:
          description: Задание успешно изменено
        401:
          description: Неавторизованный запрос
        404:
          description: Задание не найдено
        400:
          description: Запрос сформирован неверно
    delete:
      tags:
        - Task
      description: Удаление задания
      responses:
        200:
          description: Задание успешно удалено
        401:
          description: Неавторизованный запрос
        404:
          description: Задание не найдено
    #добавить патчи и действия со столбцами
components:
  schemas:
    LoginRequest:
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    RegistrationRequest:
      properties:
        email:
          type: string
        password: 
          type: string
        username:
          type: string
        avatar:
          type: string
          format: binary
      required:
        - email
        - password
        - username
    PostBoardsRequest:
      properties:
        name:
          type: string
      required:
        - name
    PostRowsRequest:
      properties:
        name:
          type: string
      required:
        - name
    PostTasksRequest:
      properties:
        name:
          type: string
      required:
        - name
        

    

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []

  
  